
var encoding = "utf-8";
var end_of_line = "\n";

var outfile = "./concat.js";

// get file system module
var fs = require('fs');
// get file list (generated by php)


var Compiler = (function(){

  var cl = require('./Classloader.js');
  
  var Compiler = function Compiler()
  {
    var classloader = new cl();

    // import methods that will be used by code to be compiled
    Package = classloader.Package;
    Import = classloader.Import;
    Extends = classloader.Extends;
    Singleton = classloader.Singleton;
    Class = classloader.Class;
    XMLResource = classloader.XMLResource;
    CSSResource = classloader.CSSResource;
    Static = classloader.Static;
    classList = classloader.classList;
    namespaces = classloader.namespaces;
    getName = classloader.getName;
  }

  Compiler.prototype.Compiler = Compiler;

  Compiler.prototype.compile = function compile()
  {
    require(outfile).code();
  }

  return Compiler;
})();


function writeNamespaces(namespaces, isroot) 
{
  var str = "";
  for(var name in namespaces)
  {
    if(isroot)
      str += "var " + name +" = {" + writeNamespaces(namespaces[name])+ "}; ";
    else
      str += name +": {" + writeNamespaces(namespaces[name])+ "},";
  }

  return str.substring(0, str.length - 1);
};

var compiler = new Compiler();
compiler.compile();

//console.log(writeNamespaces(classloader.namespaces, true));

