
var encoding = "utf-8";
var end_of_line = "\n";

var outfile = "./concat.js";

// get file system module
var fs = require('fs');
// get file list (generated by php)
var cl = require('./Classloader.js');
var classloader = new cl();

Package = classloader.Package;
Import = classloader.Import;
Extends = classloader.Extends;
Singleton = classloader.Singleton;
Class = classloader.Class;
XMLResource = classloader.XMLResource;
CSSResource = classloader.CSSResource;
Static = classloader.Static;
namespaces = classloader.namespaces;

function Compiler()
{
  require(outfile).code();
}

function writeNamespaces(namespaces, isroot) 
{
  var str = "";
  for(var name in namespaces)
  {
    if(isroot)
      str += "var " + name +" = {" + writeNamespaces(namespaces[name])+ "}; ";
    else
      str += name +": {" + writeNamespaces(namespaces[name])+ "},";
  }

  return str.substring(0, str.length - 1);
};

var compiler = new Compiler();
console.log(writeNamespaces(classloader.namespaces, true));

