// Concats files into a temp file

var encoding = "utf-8";
var end_of_line = "\n";

// get file system module
var _fs = require('fs');
// get file list (generated by php)
// var filelist = require('filelist.js');

console.log("Start ");
function Concatenator()
{
  console.log("Concatenator");
  // for (var i = 0; i < filelist.length; i++) 
  // {
  //   console.log(filelist[i]);    
  // }
}

Concatenator();