// Concats files into a temp file

var encoding = "utf-8";
var end_of_line = "\n";

var outfile = "concat.js";

// get file system module
var _fs = require('fs');
// get file list (generated by php)
var filelist = require('./filelist.js').filelist;

function Concatenator(filelist)
{
  return filelist.map(function(file){
          return _fs.readFileSync(file, encoding);
      });
}
var out = new Concatenator(filelist);
_fs.writeFileSync(outfile, out.join(end_of_line), encoding);
